<table>
    <tr>
        <td>Name</td>
        <td>Category</td>
        <td>Value</td>
    </tr>
    {stocks}
        <tr>
            <td>{Name}</td>
            <td>{Category}</td>
            <td>{Value}</td>
        </tr>
    {/stocks}
</table>